/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'tea' : null } |
  { 'meals' : null } |
  { 'snacks' : null } |
  { 'coffee' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'reward' : bigint,
  'title' : string,
  'description' : string,
  'category' : Category,
}
export interface TaskCompletion {
  'completedAt' : Time,
  'userId' : Principal,
  'taskId' : bigint,
  'approved' : boolean,
}
export type TaskStatus = { 'completed' : null } |
  { 'available' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'username' : string, 'balance' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a new task. Admin only.
   */
  'addTask' : ActorMethod<[string, string, bigint, Category], undefined>,
  /**
   * / Approve a task completion and credit the user's balance. Admin only.
   */
  'approveTaskCompletion' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a user. Admin only (enforced inside AccessControl.assignRole).
   */
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get the caller's current balance. Authenticated users only.
   */
  'getMyBalance' : ActorMethod<[], bigint>,
  /**
   * / Get the caller's task completions. Authenticated users only.
   */
  'getMyCompletions' : ActorMethod<[], Array<TaskCompletion>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all available tasks. Public — no auth required.
   */
  'listAvailableTasks' : ActorMethod<[], Array<Task>>,
  /**
   * / Register a new user. Any non-anonymous principal may call this.
   */
  'registerUser' : ActorMethod<[string], undefined>,
  /**
   * / Request a withdrawal. Authenticated users only.
   */
  'requestWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a contact form. Public — no auth required.
   */
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Submit a task completion record. Authenticated users only.
   */
  'submitTaskCompletion' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];